language: node_js
node_js:
    - node
branches:
    only:
        - master
        - /^greenkeeper-.*$/
        - /^v\d+\.\d+\.\d+(?:-rc\d+)?/
dist: trusty
cache:
  directories:
    - "node_modules"
script: npm run test -- --coverage
